sudo: false
dist: trusty
language: node_js
node_js:
  - 'node'
  - 'lts/argon'
cache:
  directories:
    - node_modules
before_script:
  # always install the appropriate version of video.js for the environment
  - npm i "video.js@$VJS";
  - pulseaudio -D
env:
  matrix:
    - VJS=5
    - VJS=6
addons:
  apt:
    # pulseaudio is needed for dockerized chrome since it has a dummy sink and
    # the dummy audio ALSA kernel module isn't loaded by Travis
    # libavcodec54 is needed by firefox for h.264 support
    packages:
      - pulseaudio
      - libavcodec54
  chrome: stable
  firefox: latest
